import type { HostedEmojiSet, SkinTone } from "emojisense";
import type { SetEmoji } from "./catalog.ts";

/**
 * The pinned upstream of each hosted set. Files are fetched from jsDelivr at the commit, so an
 * upstream change never alters a URL we already serve. Licenses and attribution: NOTICE.
 * After changing a pin, run `pnpm --filter @emojisense/worker sets` to rebuild upstreams.json.
 */
export interface Upstream {
  /** GitHub repository, served through jsDelivr's `/gh/` endpoint. */
  repo: string;
  commit: string;
  /** The release or branch state the commit belongs to, for people. */
  release: string;
  license: { spdx: string; url: string };
}

export const UPSTREAMS: Record<HostedEmojiSet, Upstream> = {
  twemoji: {
    repo: "jdecked/twemoji",
    commit: "b6b55fef1e8636b540a6d016a4729ca8cdf2e60b",
    release: "v17.0.3",
    license: { spdx: "CC-BY-4.0", url: "https://creativecommons.org/licenses/by/4.0/" },
  },
  noto: {
    repo: "googlefonts/noto-emoji",
    commit: "e20cbc2bbec1926686be9f9bee7d1d2cfa1fea0e",
    release: "v2026-09-24-unicode18_0",
    license: { spdx: "Apache-2.0", url: "https://www.apache.org/licenses/LICENSE-2.0" },
  },
  fluent: {
    repo: "microsoft/fluentui-emoji",
    commit: "1ffb34c752ecf5d402f04cfb4b392c77f57c54bc",
    release: "main, 2026-08-24",
    license: { spdx: "MIT", url: "https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE" },
  },
};

export function isHostedSet(value: string): value is HostedEmojiSet {
  return Object.hasOwn(UPSTREAMS, value);
}

/** Generated by scripts/check-sets.ts from the upstream file listings (upstreams.json). */
export interface UpstreamData {
  twemoji: RuleSetData;
  noto: RuleSetData;
  fluent: FluentData;
}

interface SetData {
  /** The pin the data was built for; must equal `UPSTREAMS[set].commit`. */
  commit: string;
  /** Canonical hexcode → English label of each emoji the upstream does not draw. */
  missing: Record<string, string>;
}

/** Sets whose file names follow from the code points. */
export interface RuleSetData extends SetData {
  /** Hexcode → repository path, where the naming rule does not match the upstream file. */
  overrides: Record<string, string>;
}

export interface FluentData extends SetData {
  /**
   * Base hexcode → repository path of the "Flat" SVG. For emoji with skin tones it is the
   * `Default` tone; the other tones replace that directory and file suffix.
   */
  files: Record<string, string>;
}

const ZERO_WIDTH_JOINER = 0x200d;
const VARIATION_SELECTOR_16 = 0xfe0f;
const BLACK_FLAG = 0x1f3f4;
const isRegionalIndicator = (codePoint: number) => codePoint >= 0x1f1e6 && codePoint <= 0x1f1ff;
const isTag = (codePoint: number) => codePoint >= 0xe0020 && codePoint <= 0xe007f;
const codePointsOf = (emoji: string) => Array.from(emoji, (char) => char.codePointAt(0) as number);

/** Twemoji's own rule (`grabTheRightIcon`): U+FE0F stays only in ZWJ sequences; lowercase hex. */
export function twemojiPath(emoji: string): string {
  const codePoints = codePointsOf(emoji);
  const kept = codePoints.includes(ZERO_WIDTH_JOINER)
    ? codePoints
    : codePoints.filter((codePoint) => codePoint !== VARIATION_SELECTOR_16);
  return `assets/svg/${kept.map((codePoint) => codePoint.toString(16)).join("-")}.svg`;
}

/**
 * Noto names files `emoji_u<hex>_<hex>.svg` without U+FE0F. Country and subdivision flags are the
 * waved flags the Noto font uses; everything else is in `2D/svg`.
 */
export function notoPath(emoji: string): string {
  const codePoints = codePointsOf(emoji).filter((codePoint) => codePoint !== VARIATION_SELECTOR_16);
  const name = `emoji_u${codePoints.map((codePoint) => codePoint.toString(16).padStart(4, "0")).join("_")}.svg`;
  const [first = 0, second = 0] = codePoints;
  const flag =
    (codePoints.length === 2 && isRegionalIndicator(first) && isRegionalIndicator(second)) ||
    (first === BLACK_FLAG && isTag(second));
  return flag ? `third_party/region-flags/waved-svg/${name}` : `2D/svg/${name}`;
}

const FLUENT_TONES: Record<Exclude<SkinTone, "none">, string> = {
  light: "Light",
  "medium-light": "Medium-Light",
  medium: "Medium",
  "medium-dark": "Medium-Dark",
  dark: "Dark",
};

/** Fluent keeps each emoji in a folder named after it; tones are sibling folders of `Default`. */
export function fluentPath(entry: SetEmoji, files: Readonly<Record<string, string>>): string | undefined {
  const path = files[entry.base];
  if (!path || entry.tone === "none") return path;
  if (!path.includes("/Default/Flat/")) return undefined;
  return path
    .replace("/Default/Flat/", `/${FLUENT_TONES[entry.tone]}/Flat/`)
    .replace(/_default\.svg$/, `_${entry.tone}.svg`);
}

export type UpstreamResolver = (set: HostedEmojiSet, entry: SetEmoji) => string | undefined;

/** Repository path of an emoji in a set, or undefined when the pinned upstream does not draw it. */
export function createUpstreamResolver(data: UpstreamData): UpstreamResolver {
  const missing = {
    twemoji: new Set(Object.keys(data.twemoji.missing)),
    noto: new Set(Object.keys(data.noto.missing)),
    fluent: new Set(Object.keys(data.fluent.missing)),
  };
  return (set, entry) => {
    if (missing[set].has(entry.hexcode)) return undefined;
    switch (set) {
      case "twemoji":
        return data.twemoji.overrides[entry.hexcode] ?? twemojiPath(entry.emoji);
      case "noto":
        return data.noto.overrides[entry.hexcode] ?? notoPath(entry.emoji);
      case "fluent":
        return fluentPath(entry, data.fluent.files);
    }
  };
}

/** The immutable jsDelivr URL of a repository path at the pinned commit. */
export function upstreamUrl(set: HostedEmojiSet, path: string): string {
  const { repo, commit } = UPSTREAMS[set];
  return `https://cdn.jsdelivr.net/gh/${repo}@${commit}/${path.split("/").map(encodeURIComponent).join("/")}`;
}
