/**
 * Writes src/culture/zones.generated.ts: IANA time zone → ISO 3166-1 alpha-2 region, from the
 * tz database's zone.tab, plus the names browsers report for the same zones (ICU still says
 * "Asia/Calcutta" where IANA says "Asia/Kolkata"). Culture files carry the part of this table
 * that their entries' regions need, so a device without a region in its language can still
 * find one from its time zone (docs/PACK_FORMAT.md §9).
 *
 *   pnpm --filter @emojisense/data culture:zones [path/to/zone.tab]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DATA_ROOT } from "../src/paths.ts";

const source = process.argv[2] ?? join(process.env.TZDIR ?? "/usr/share/zoneinfo", "zone.tab");
const resolved = (zone: string): string | undefined => {
  try {
    return new Intl.DateTimeFormat("en", { timeZone: zone }).resolvedOptions().timeZone;
  } catch {
    return undefined;
  }
};

const regions = new Map<string, string>();
for (const line of readFileSync(source, "utf8").split("\n")) {
  if (line === "" || line.startsWith("#")) continue;
  const [codes, , zone] = line.split("\t");
  // zone.tab has one country per line; zone1970.tab (comma lists) would not name one region.
  if (!codes || !zone || !/^[A-Z]{2}$/.test(codes)) continue;
  regions.set(zone, codes);
  const icu = resolved(zone);
  if (icu && !regions.has(icu)) regions.set(icu, codes);
}
for (const zone of Intl.supportedValuesOf("timeZone")) {
  const icu = resolved(zone);
  const region = icu ? regions.get(icu) : undefined;
  if (region && !regions.has(zone)) regions.set(zone, region);
}

const sorted = [...regions].sort(([a], [b]) => (a < b ? -1 : 1));
const body = sorted.map(([zone, region]) => `  "${zone}": "${region}",`).join("\n");
const out = join(DATA_ROOT, "src", "culture", "zones.generated.ts");
writeFileSync(
  out,
  `// Generated by scripts/make-zones.ts from the tz database's zone.tab. Do not edit.\n` +
    `/** IANA (and ICU) time zone → ISO 3166-1 alpha-2 region. */\n` +
    `export const ZONE_REGIONS: Readonly<Record<string, string>> = {\n${body}\n};\n`,
);
console.log(`${sorted.length} zones → ${out}`);
