/**
 * Writes Sources/Emojisense/FunctionWords.swift: the function-word lists of the reference engine
 * (FUNCTION_WORDS in packages/core/src/function-words.ts, PACK_FORMAT.md §4). Run it after a list
 * changes, then regenerate golden.json, whose `functionWords` section the conformance tests check.
 *
 *   pnpm exec tsx sdks/swift/scripts/make-function-words.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { FUNCTION_WORDS } from "../../../packages/core/src/function-words.ts";

const OUTPUT = fileURLToPath(new URL("../Sources/Emojisense/FunctionWords.swift", import.meta.url));
const LINE_LENGTH = 88;

/** The words as lines of at most LINE_LENGTH code points, joined by spaces. */
function lines(words: readonly string[]): string[] {
  const out: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if ([...next].length > LINE_LENGTH && line) {
      out.push(line);
      line = word;
    } else line = next;
  }
  if (line) out.push(line);
  return out;
}

const entries = Object.entries(FUNCTION_WORDS).map(([locale, words]) =>
  [`    "${locale}": [`, ...lines(words).map((line) => `      ${JSON.stringify(line)},`), "    ],"].join(
    "\n",
  ),
);
const source = `// Generated by sdks/swift/scripts/make-function-words.ts from packages/core/src/function-words.ts.
// Do not edit.

/// Function words per pack locale (PACK_FORMAT.md §4, "Function words"): normalized, one token each.
enum FunctionWords {
  /// Space-separated words per locale, in the reference order.
  static let lines: [String: [String]] = [
${entries.join("\n")}
  ]

  /// The words of every list, as the reference \`FUNCTION_WORDS\` holds them.
  static let lists: [String: [String]] = lines.mapValues { rows in
    rows.joined(separator: " ").split(separator: " ").map(String.init)
  }

  /// Lists that apply to every query whatever its locale.
  static let alwaysActive = ["en", "tr"]

  /// Keyed by exact UTF-16 code units, like the vocabulary (\`AliasIndex\`).
  private static let activeByLocale: [String: Set<UTF16Text>] = lists.mapValues { words in
    Set((alwaysActive.flatMap { lists[$0] ?? [] } + words).map { Array($0.utf16) })
  }

  /// The function words of a query in \`locale\`: its own list plus the en and tr lists; for a
  /// locale without a list, the en and tr lists only.
  static func active(forLocale locale: String) -> Set<UTF16Text> {
    activeByLocale[locale] ?? activeByLocale["en"] ?? []
  }
}
`;
writeFileSync(OUTPUT, source);
console.log(`make-function-words: ${Object.keys(FUNCTION_WORDS).length} locales → ${OUTPUT}`);
