/**
 * Writes Sources/Emojisense/UnicodeReference.swift: the Unicode data of the TypeScript reference
 * runtime that the Swift normalizer needs and cannot get from the platform.
 *
 * - The Unicode version: the Swift normalizer treats newer code points as unassigned, as the
 *   reference does, so a newer OS does not change normalization.
 * - The code points that normalization step 2 (docs/PACK_FORMAT.md §3) replaces with a space.
 *   Swift has no public `Extended_Pictographic` property.
 *
 * Both come from this Node runtime, evaluated with the regular expression of
 * packages/core/src/normalize.ts.
 *
 *   pnpm exec tsx sdks/swift/scripts/make-unicode-tables.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Keep in sync with EMOJI_PARTS in packages/core/src/normalize.ts. */
const EMOJI_PARTS =
  /^[\p{Extended_Pictographic}\p{Emoji_Modifier}\p{Regional_Indicator}\u{E0020}-\u{E007F}]$/u;
const MAX_CODE_POINT = 0x10ffff;
const OUTPUT = fileURLToPath(new URL("../Sources/Emojisense/UnicodeReference.swift", import.meta.url));

function collectRanges(): [number, number][] {
  const ranges: [number, number][] = [];
  for (let cp = 0; cp <= MAX_CODE_POINT; cp++) {
    if (!EMOJI_PARTS.test(String.fromCodePoint(cp))) continue;
    const last = ranges.at(-1);
    if (last && last[1] === cp - 1) last[1] = cp;
    else ranges.push([cp, cp]);
  }
  return ranges;
}

const hex = (cp: number) => `0x${cp.toString(16).toUpperCase().padStart(4, "0")}`;
const ranges = collectRanges();
const unicode = process.versions.unicode;
if (!unicode) throw new Error("This Node runtime does not report its Unicode version");
const [major, minor] = unicode.split(".").map(Number);
const lines = [
  `// Generated by sdks/swift/scripts/make-unicode-tables.ts from Node ${process.versions.node}.`,
  "// Do not edit.",
  "",
  "/// Unicode data of the TypeScript reference runtime.",
  "enum UnicodeReference {",
  `  /// Unicode ${unicode}. Code points assigned later are unassigned for the reference engine.`,
  `  static let version: Unicode.Version = (major: ${major}, minor: ${minor})`,
  "",
  "  /// Code points that normalization step 2 replaces with a space (PACK_FORMAT.md §3):",
  "  /// Extended_Pictographic, Emoji_Modifier, Regional_Indicator and U+E0020–U+E007F.",
  "  /// Sorted, disjoint, inclusive ranges.",
  "  static let emojiPartRanges: [ClosedRange<UInt32>] = [",
  ...ranges.map(([lo, hi]) => `    ${hex(lo)}...${hex(hi)},`),
  "  ]",
  "}",
  "",
];
writeFileSync(OUTPUT, lines.join("\n"));
console.log(`make-unicode-tables: Unicode ${unicode}, ${ranges.length} emoji part ranges → ${OUTPUT}`);
